### ISSUE TITLE
Type of emergency services needed

### ISSUE THREAD

**Issue by gregorwmail** [ServiceNowDevProgram/911-Dispatcher-Workspace#18]
Add check boxes which will indicate emergency services needed, e.g. Fire, Police, EMS, Utility or multiple services e.g. Fire + Police.

**Comment by TRIGGEREDcoder** [comment]
Please assign this issue to me.

**Comment by TRIGGEREDcoder** [comment]
@gregorwmail @csharpie Emergency type list field has been added on the table but the field cant be edited on workspace side. Can you create this issue and assign to me. I will have to create a table to store the choices else we need to disable oob script.
![image](https://github.com/ServiceNowDevProgram/911-Dispatcher-Workspace/assets/43340158/033fdc07-83d0-4b93-94d5-4993f0ce40fd)

**Comment by csharpie** [comment]
Hey @TRIGGEREDcoder. Issues are open to anyone to create. I created one yesterday and worked on it; you can just mention you are working on the one you've opened. I don't believe ServiceNowDevs have a formal process for assignment of issues but I can't say for sure. I'm just a regular ol' Hacktober participant. Happy Hacking!

**Comment by TRIGGEREDcoder** [comment]
sure thanks
