### ISSUE TITLE
Adjust Create button's on click event to format the description of the emergency record

### ISSUE THREAD

**Issue by csharpie** [ServiceNowDevProgram/911-Dispatcher-Workspace#47]
When you click the Create button on the _Home with emergency call_ landing page, the description field of the newly created x_snc_911_operat_0_emergency record has the following formatting:

  _Caller number: {caller_number_from_landing_page} | Description{description_from_landing_page}_

There should be a space and a  _:_ following the _description_.

**Comment by shreyverma03** [comment]
Please assign this to me

**Comment by csharpie** [comment]
I’ve worked on this already. My pull request is linked.
