### ISSUE TITLE
When a new Emergency record is created, either auto assign via round robin or allow self assignment

### ISSUE THREAD

**Issue by MGOPW** [ServiceNowDevProgram/911-Dispatcher-Workspace#5]
When emergency record is created from landing page(#1 ), allow operator to self assign or set it to be round robin assigned to another operator.

**Comment by sanjivmeher** [comment]
Could you please assign it to me? Is this the expectation. On an emergency record, a button to Assign to self or to a person when assigned to an assignment group.

<img width="1045" alt="image" src="https://github.com/ServiceNowDevProgram/911-Dispatcher-Workspace/assets/7389436/7833a37b-d021-4ec1-b00f-8dd2e6034ccd">

**Comment by MGOPW** [comment]
@sanjivmeher - This is the record page. I'd like there to be a mechanism for operators to be able to quickly create a record and assign it to themselves from the landing page.

**Comment by shreyverma03** [comment]
Has this issue got fixed?

**Comment by sanjivmeher** [comment]
> Has this issue got fixed?

Not Sure...I haven't fixed it so you can go aheat with it.. @shreyverma03
