### ISSUE TITLE
Create a button to dispatch an emergency response from record page of workspace

### ISSUE THREAD

**Issue by MGOPW** [ServiceNowDevProgram/911-Dispatcher-Workspace#6]
There should be four buttons, with icons/images, that depict Fire/Police/EMS/Utility agency, and when clicked they update the record to be assigned to the agency and saved in one touch.

**Comment by sanjivmeher** [comment]
@MGOPW Do you want a comment to be added or is there an agency field on the form which needs to be updated?

**Comment by Rampriya-S** [comment]
Response dispatched buttons #30 Four buttons created for Response dispatch.
