### ISSUE TITLE
Create a 911 dispatcher playbook

### ISSUE THREAD

**Issue by MGOPW** [ServiceNowDevProgram/911-Dispatcher-Workspace#9]
Create a playbook to show how to handle emergency calls.

**Comment by puneet94** [comment]
I have installed plugins for Playbook and Process Automation Designer( https://github.com/ServiceNowDevProgram/911-Dispatcher-Workspace/pull/20 ). I will continue working on the playbooks. Can you please assign this to me?

**Comment by SapphicFire** [comment]
Assigned to you @puneet94

**Comment by Lacah** [comment]
@puneet94 would you reckon it can be closed following your PR #41 ?
